packages:
  - 'action-bars'
  - 'ag-grid'
  - 'angular-tree-component'
  - 'autonumeric'
  - 'avatar'
  - 'colorpicker'
  - 'core'
  - 'data-manager'
  - 'datetime'
  - 'errors'
  - 'flyout'
  - 'forms'
  - 'grids'
  - 'indicators'
  - 'inline-form'
  - 'layout'
  - 'list-builder'
  - 'list-builder-view-checklist'
  - 'list-builder-view-grids'
  - 'lists'
  - 'lookup'
  - 'modals'
  - 'navbar'
  - 'pages'
  - 'phone-field'
  - 'popovers'
  - 'progress-indicator'
  - 'select-field'
  - 'split-view'
  - 'tabs'
  - 'text-editor'
  - 'theme'
  - 'tiles'
  - 'toast'
  - 'validation'
